### PR TITLE
Expose the `hb_subset_input_pin_all_axes_to_default` function in the `hb-subset` build

### PR DESCRIPTION
**Pull request by nk-coding**
Exposes `hb_subset_input_pin_all_axes_to_default` (according to docs available since 8.3.1)
Having this would help me a lot migrating my project to harfbuzz, but I think others could potentially benefit from this, too

### CODE REVIEW

**Comment by khaledhosny** [comment]
Thanks!

**Comment by nk-coding** [comment]
@khaledhosny I'd like to ask if you maybe could consider publishing a new release. Already thanks a lot in advance

**Comment by khaledhosny** [comment]
> @khaledhosny I'd like to ask if you maybe could consider publishing a new release. Already thanks a lot in advance

https://github.com/harfbuzz/harfbuzzjs/releases/tag/v0.4.2
https://www.npmjs.com/package/harfbuzzjs/v/0.4.2

**Comment by nk-coding** [comment]
> https://github.com/harfbuzz/harfbuzzjs/releases/tag/v0.4.2 
> https://www.npmjs.com/package/harfbuzzjs/v/0.4.2

thanks a lot

**Pull request merged**
