### PR TITLE
Added TypeScript bindings and refactored shape method

### PR DESCRIPTION
**Pull request by Harachie**
Hi HarfBuzz masters,

if you like, you can merge this one.
It contains type script bindings, an easy load method for the wasm,
a simple shape method and the method to get the em size from the font face.

Thank you so much for your awesome library!
Your way to build the wasm is the best I found so far :).

Kind regards

### CODE REVIEW

**Comment by ebraminio** [comment]
Thank you! Looks very good! Can we avoid having that feeling cryptic hbjs.js.map in repo? Would be nice to use two space indents if is possible. And guess we should adopt ES6 classes instead providing interfaces now that ES6 is a must thus removing those create* APIs, something like what Khaled [has done](https://github.com/alif-type/rana-kufi/blob/master/docs/HarfBuzz.js), maybe in a separate wrapper deprecating hbjs later. What command you use to compile TS btw? Thanks!

**Comment by Harachie** [comment]
Sure, I will remove the map file. It's usefull for directly debugging the .ts file, but TypeScript will automatically create it on compilation.
Sure, I will adopt the 2 space indents!
Classes makes sense for me as well.
Gonna work on it now.

Thanks for the feedback!

**Comment by Harachie** [comment]
Forgot to mention command:
It's just tsc (it will grab the tsconfig and check the options there).
Currently it's set to transpile to ES6 module syntax.

**Comment by Harachie** [comment]
refactored to be class based.
What do you think?

**Comment by Harachie** [comment]
sry forgot the 2 space indent... will fix

**Comment by Harachie** [comment]
now with correct indentation

**Comment by ebraminio** [comment]
Looks fantastic now! Now can we have a different naming for the work? I like to deprecate hbjs.js gradually as there are clients that rely to it by encouraging use of it by introducing new features to the work instead, like the great ones you've added already! :)

**Comment by Harachie** [comment]
What name do you propose?
Maybe "harfbuzz.ts" which would be transpiled to harfbuzz.js ?

**Comment by ebraminio** [comment]
Oh, I didn't notice the changes, looks fantastic! Thank you very much :)

**Pull request merged**
