### PR TITLE
New: Use the latest harfbuzz to build hb-subset.wasm

### PR DESCRIPTION
**Pull request by yisibl**
The current subset cannot properly subset the COLR/CPAL fonts. 

1. Open https://harfbuzz.github.io/harfbuzzjs/subset/
2. Drag and drop colr-table.ttf
3. Enter `abc`, the font actually downloaded cannot be used.

After rebuilt the WASM file, it is fine.

### CODE REVIEW

**Comment by yisibl** [comment]
@ebraminio @khaledhosny PTAL

**Comment by papandreou** [comment]
I also [ran into a bug that's already fixed in harfbuzz](https://github.com/Munter/subfont/issues/141#issuecomment-816277047), so +1 to getting a new harfbuzzjs release out.

In the mean time I've released a fork called `harfbuzzjs-papandreou`.

**Comment by papandreou** [comment]
Thanks, @ebraminio 🎉

**Comment by ebraminio** [comment]
@papandreou Thank you! Just let me know whenever you wanted another update :)

@yisibl Just updated https://harfbuzz.github.io/harfbuzzjs/subset/ and enabled subset of GPOS/GSUB/GDEF also, let me know if any other thing is needed to your use case :)

**Comment by yisibl** [comment]
Thanks, @ebraminio 

Can this issue(https://github.com/harfbuzz/harfbuzz/issues/1017) be closed now? 

It would be better if it could be stated in the document which tables support subset.

**Comment by ebraminio** [comment]
@yisibl Oh, the latest update I have from them is they are almost complete by not finished yet, for the demo I had to enable them manually and that is also what @papandreou in https://github.com/papandreou/subset-font also, hopefully soon they can be declared finished so we can remove the manual enabling code :)

**Comment by yisibl** [comment]
@ebraminio Nice! 

Are there any plans for https://github.com/harfbuzz/harfbuzz/issues/2843?

**Comment by behdad** [comment]
The GSUB/GPOS subsetting indeed is complete. We are going to flip it on by default.
COLR/CPAL subsetting also should work already.

**Comment by yisibl** [comment]
Fixed in https://github.com/harfbuzz/harfbuzz/pull/2970

**Pull request closed without merging**
